kind: Pod
apiVersion: v1
metadata:
  name: testpod
  annotations:
    description: our first testing pods
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Test message; sleep 5; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello from c01; sleep 5; done"]
    - name: c02
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello from c02; sleep 5; done"]
  restartPolicy: Never

