kind: ReplicationController               
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2            
  selector:        
    myname: yash
  template:                
    metadata:
      name: testpod6
      labels:            
        myname: yash
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Yash; sleep 5 ; done"]


